#!/usr/bin/env python

import threading

try:
    import flydra.camnode
except ImportError:
    import sys
    import os.path
    sys.path.insert(0, os.path.expanduser("~/flydra.git"))
    import flydra.camnode

import roslib; roslib.load_manifest('rospy')
import rospy

def main():
    rospy.init_node('flydra_camnode')

    spinthread = threading.Thread(target=rospy.spin)
    spinthread.start()

    flydra.camnode.main(
        rospy_init_node=False,  #we have already done that
        cmdline_args=rospy.myargv()[1:]
    )

    rospy.signal_shutdown("quit")

if __name__ == '__main__':
    main()

